### ISSUE TITLE
Segfault after deleting user and going back to main view

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/switchboard-plug-useraccounts#155]
## Steps to Reproduce

1. Delete a user
2. Go back to the main Switchboard view by clicking the "All Settings" button
3. Observe crash

## Platform Information
6.0 Odin - current daily or compiled from git

**Comment by meisenzahl** [comment]
I can reproduce this if I create a new user and delete it immediately.

```
(io.elementary.switchboard:3228): accountsservice-CRITICAL **: 12:43:39.901: act_user_get_user_name: assertion 'ACT_IS_USER (user)' failed
Segmentation fault
```

However, I cannot reproduce it when I delete a user that existed before.

**Comment by meisenzahl** [comment]
@davidmhewitt do you think this could be a bug in `libaccountsservice`?

```
#0  0x00007ffff7ebf494 in g_str_hash () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7ebdfcc in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fffd76e0075 in  () at /lib/x86_64-linux-gnu/libaccountsservice.so.0
#3  0x00007ffff6f5aff5 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#4  0x00007ffff6f5a40a in  () at /lib/x86_64-linux-gnu/libffi.so.7
#5  0x00007ffff7c5330d in g_cclosure_marshal_generic () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7c52802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7c66814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7c70a37 in g_signal_emitv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007fffd76e4be5 in  () at /lib/x86_64-linux-gnu/libaccountsservice.so.0
#10 0x00007ffff7c52802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7c65f96 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff7c71b9e in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7c720d3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7db9f00 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff7da792f in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007ffff7ed0e8e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff7ed1240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff7ed1533 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff760a37d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x000055555555f22c in  ()
#21 0x00007ffff7c52a56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff7c71b28 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7c720d3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff7d80d88 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#25 0x00007ffff7d80f42 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#26 0x000055555555f571 in switchboard_main ()
#27 0x00007ffff70ee0b3 in __libc_start_main (main=0x55555555d100 <main>, argc=1, argv=0x7fffffffdc68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc58) at ../csu/libc-start.c:308
#28 0x000055555555d14e in _start ()
```

**Comment by davidmhewitt** [comment]
I think it's unlikely to be a bug in accountsservice (but you never know!), my guess would be something is going out of scope when the plug is closed and we're ending up passing null pointers to accountsservice or something.
